spring.application.name=note
spring.datasource.url=jdbc:postgresql://localhost:5432/notesdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

# Blockfrost (Preview network)
# Provide your Blockfrost Project ID via env var BLOCKFROST_PROJECT_ID or set directly here.
blockfrost.api.base=https://cardano-preview.blockfrost.io/api/v0
blockfrost.project.id=previewjlxSlBwl9F6K4hnLfDIP0EDeOBG4mvxt
blockfrost.baseUrl=${blockfrost.api.base}
blockfrost.projectId=${blockfrost.project.id}